---
kind: pipeline
name: discovery-service

steps:
  - name: build-discovery-service
    image: gradle:4.8-jdk8-slim
    privileged: true
    commands:
      - gradle :discovery-service:build
    volumes:
      - name: gradle_cache
        path: /drone/gradle

trigger:
  event:
    - push
  branch:
    - master
    - development

volumes:
  - name: gradle_cache
    host:
      path: /tmp/gradle_cache
