version: "3"

# =====================================
# docker file for local run or showcase
# make sure to run first:
#   ./gradlew clean bootJar
# then:
#   docker-compose up
# =====================================

services:
  mongodb:
    image: "bitnami/mongodb:latest"
    ports:
      - "32768:27017"
    volumes:
      - "astrea-local-mongodb-data:/bitnami"
  authorization-service:
    build: ./authorization-service
    ports:
      - "8180:8080"
  token-proxy:
    build: ./token-proxy
    depends_on:
      - client-service
      - discovery-service
      - authorization-service
    ports:
      - "9190:8080"
    environment:
      - CLIENT_SERVICE_HOST=client-service
      - CLIENT_SERVICE_PORT=35027
      - DISCOVERY_SERVICE_HOST=discovery-service
      - DISCOVERY_SERVICE_PORT=35028
      - TOKEN_ENDPOINT_HOST=authorization-service
      - TOKEN_ENDPOINT_PORT=8080
  client-service:
    build: ./client-service
    depends_on:
      - mongodb
      - discovery-service
    ports:
      - "8280:8080"
      - "35027:35027"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - DISCOVERY_HOST=discovery-service
      - DISCOVERY_PORT=35028
  discovery-service:
    build: ./discovery-service
    ports:
      - "8380:8080"
      - "35028:35028"

volumes:
  astrea-local-mongodb-data: