version: "3"

services:
  mongodb:
    image: "bitnami/mongodb:latest"
    ports:
      - "32768:27017"
    volumes:
      - "astrea-local-mongodb-data:/bitnami"
  redis:
    image: "bitnami/redis:latest"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
    ports:
      - "6379:6379"
    volumes:
      - "astrea-local-redis-data:/bitnami/redis/data"
  mysql:
    image: "bitnami/mysql:latest"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
    ports:
      - "3306:3306"
    volumes:
      - "astrea-local-mysql-data:/bitnami/mysql/data"

volumes:
  astrea-local-mongodb-data:
  astrea-local-redis-data:
  astrea-local-mysql-data: