package io.imulab.astrea.sdk.discovery

data class Discovery(
    override val issuer: String = "",
    override var authorizationEndpoint: String = "",
    override var tokenEndpoint: String = "",
    override var userInfoEndpoint: String = "",
    override var jwksUri: String = "",
    override var registrationEndpoint: String = "",
    override var scopesSupported: MutableList<String> = mutableListOf(),
    override var responseTypesSupported: MutableList<String> = mutableListOf(),
    override var responseModeSupported: MutableList<String> = mutableListOf(),
    override var grantTypesSupported: MutableList<String> = mutableListOf(),
    override var acrValuesSupported: MutableList<String> = mutableListOf(),
    override var subjectTypesSupported: MutableList<String> = mutableListOf(),
    override var idTokenSigningAlgorithmValuesSupported: MutableList<String> = mutableListOf(),
    override var idTokenEncryptionAlgorithmValuesSupported: MutableList<String> = mutableListOf(),
    override var idTokenEncryptionEncodingValuesSupported: MutableList<String> = mutableListOf(),
    override var userInfoSigningAlgorithmValuesSupported: MutableList<String> = mutableListOf(),
    override var userInfoEncryptionAlgorithmValuesSupported: MutableList<String> = mutableListOf(),
    override var userInfoEncryptionEncodingValuesSupported: MutableList<String> = mutableListOf(),
    override var requestObjectSigningAlgorithmValuesSupported: MutableList<String> = mutableListOf(),
    override var requestObjectEncryptionAlgorithmValuesSupported: MutableList<String> = mutableListOf(),
    override var requestObjectEncryptionEncodingValuesSupported: MutableList<String> = mutableListOf(),
    override var tokenEndpointAuthenticationMethodsSupported: MutableList<String> = mutableListOf(),
    override var tokenEndpointAuthenticationSigningAlgorithmValuesSupported: MutableList<String> = mutableListOf(),
    override var displayValuesSupported: MutableList<String> = mutableListOf(),
    override var claimTypesSupported: MutableList<String> = mutableListOf(),
    override var claimsSupported: MutableList<String> = mutableListOf(),
    override var serviceDocumentation: String = "",
    override var claimsLocalesSupported: MutableList<String> = mutableListOf(),
    override var uiLocalesSupported: MutableList<String> = mutableListOf(),
    override var claimsParameterSupported: Boolean = false,
    override var requestParameterSupported: Boolean = false,
    override var requestUriParameterSupported: Boolean = false,
    override var requireRequestUriRegistration: Boolean = false,
    override var opPolicyUri: String = ""
) : io.imulab.astrea.sdk.oidc.discovery.Discovery {
    companion object {
        fun fromDiscoveryResponse(response: DiscoveryResponse) : Discovery {
            return Discovery(
                issuer = response.issuer,
                authorizationEndpoint = response.authorizationEndpoint,
                tokenEndpoint = response.tokenEndpoint,
                userInfoEndpoint = response.userInfoEndpoint,
                jwksUri = response.jwksUri,
                registrationEndpoint = response.registrationEndpoint,
                scopesSupported = response.scopesSupportedList,
                responseTypesSupported = response.responseTypesSupportedList,
                responseModeSupported = response.responseModeSupportedList,
                grantTypesSupported = response.grantTypesSupportedList,
                acrValuesSupported = response.acrValuesSupportedList,
                subjectTypesSupported = response.subjectTypesSupportedList,
                idTokenSigningAlgorithmValuesSupported = response.idTokenSigningAlgorithmValuesSupportedList,
                idTokenEncryptionAlgorithmValuesSupported = response.idTokenEncryptionAlgorithmValuesSupportedList,
                idTokenEncryptionEncodingValuesSupported = response.idTokenEncryptionEncodingValuesSupportedList,
                userInfoSigningAlgorithmValuesSupported = response.userInfoSigningAlgorithmValuesSupportedList,
                userInfoEncryptionAlgorithmValuesSupported = response.userInfoEncryptionAlgorithmValuesSupportedList,
                userInfoEncryptionEncodingValuesSupported = response.userInfoEncryptionEncodingValuesSupportedList,
                requestObjectSigningAlgorithmValuesSupported = response.requestObjectSigningAlgorithmValuesSupportedList,
                requestObjectEncryptionAlgorithmValuesSupported = response.requestObjectEncryptionAlgorithmValuesSupportedList,
                requestObjectEncryptionEncodingValuesSupported = response.requestObjectEncryptionEncodingValuesSupportedList,
                tokenEndpointAuthenticationMethodsSupported = response.tokenEndpointAuthenticationMethodsSupportedList,
                tokenEndpointAuthenticationSigningAlgorithmValuesSupported = response.tokenEndpointAuthenticationSigningAlgorithmValuesSupportedList,
                displayValuesSupported = response.displayValuesSupportedList,
                claimTypesSupported = response.claimTypesSupportedList,
                claimsSupported = response.claimsSupportedList,
                uiLocalesSupported = response.uiLocalesSupportedList,
                claimsParameterSupported = response.claimsParameterSupported,
                requestParameterSupported = response.requestParameterSupported,
                requestUriParameterSupported = response.requestUriParameterSupported,
                requireRequestUriRegistration = response.requireRequestUriRegistration,
                opPolicyUri = response.opPolicyUri
            )
        }
    }
}