openapi: 3.0.0

info:
  title: "Astrea Client API"
  description: "Astrea Client API in conformance to Open ID Connect 1.0 Dynamic Client Registration."
  contact:
    name: "Weinan Qiu"
    url: https://github.com/imulab
  license:
    name: "Apache 2.0"
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0

paths:
  /client:
    post:
      summary: "Creating an Open ID Connect 1.0 client."
      operationId: client.create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewClientRequest"
      responses:
        201:
          description: "Successfully created a new client"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewClientResponse"
        default:
          description: "Error response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /client/{clientId}:
    get:
      summary: "Reading client configuration by its client_id."
      operationId: client.read
      parameters:
      - in: path
        name: clientId
        schema:
          type: string
        required: true
      responses:
        200:
          description: "Read client is successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReadClientResponse"
        default:
          description: "Error response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    NewClientRequest:
      required:
      - redirect_uris
      properties:
        client_name:
          type: string
        client_type:
          type: string
          enum:
          - public
          - confidential
          default: confidential
        scopes:
          type: array
          items:
            type: string
        redirect_uris:
          type: array
          minItems: 1
          uniqueItems: true
          items:
            type: string
            format: uri
        response_types:
          type: array
          uniqueItems: true
          items:
            type: string
            enum:
            - code
            - token
            - id_token
            default: code
        grant_types:
          type: array
          uniqueItems: true
          items:
            type: string
            enum:
            - authorization_code
            - implicit
            - client_credentials
            - refresh_token
            default: authorization_code
        application_type:
          type: string
          enum:
          - web
          - native
          default: web
        contacts:
          type: array
          items:
            type: string
            format: email
        logo_uri:
          type: string
          format: uri
        client_uri:
          type: string
          format: uri
        policy_uri:
          type: string
          format: uri
        tos_uri:
          type: string
          format: uri
        jwks_uri:
          type: string
          format: uri
        jwks:
          type: string
          format: jwks
        sector_identifier_uri:
          type: string
          format: uriHttps
        subject_type:
          type: string
          enum:
          - public
          - pairwise
          default: public
        id_token_signed_response_alg:
          type: string
          enum:
          - HS256
          - HS384
          - HS512
          - RS256
          - RS384
          - RS512
          - PS256
          - PS384
          - PS512
          - ES256
          - ES384
          - ES512
          - none
          default: RS256
        id_token_encrypted_response_alg:
          type: string
          enum:
          - RSA1_5
          - RSA-OAEP
          - RSA-OAEP-256
          - ECDH-ES
          - ECDH-ES+A128KW
          - ECDH-ES+A192KW
          - ECDH-ES+A256KW
          - A128KW
          - A192KW
          - A256KW
          - A128GCMKW
          - A192GCMKW
          - A256GCMKW
          - PBES2-HS256+A128KW
          - PBES2-HS384+A192KW
          - PBES2-HS512+A256KW
          - dir
          - none
          default: none
        id_token_encrypted_response_enc:
          type: string
          enum:
          - A128CBC-HS256
          - A192CBC-HS384
          - A192CBC-HS512
          - A128GCM
          - A192GCM
          - A256GCM
          - none
          default: none
        userinfo_signed_response_alg:
          type: string
          enum:
          - HS256
          - HS384
          - HS512
          - RS256
          - RS384
          - RS512
          - PS256
          - PS384
          - PS512
          - ES256
          - ES384
          - ES512
          - none
          default: none
        userinfo_encrypted_response_alg:
          type: string
          enum:
          - RSA1_5
          - RSA-OAEP
          - RSA-OAEP-256
          - ECDH-ES
          - ECDH-ES+A128KW
          - ECDH-ES+A192KW
          - ECDH-ES+A256KW
          - A128KW
          - A192KW
          - A256KW
          - A128GCMKW
          - A192GCMKW
          - A256GCMKW
          - PBES2-HS256+A128KW
          - PBES2-HS384+A192KW
          - PBES2-HS512+A256KW
          - dir
          - none
          default: none
        userinfo_encrypted_response_enc:
          type: string
          enum:
          - A128CBC-HS256
          - A192CBC-HS384
          - A192CBC-HS512
          - A128GCM
          - A192GCM
          - A256GCM
          - none
          default: none
        request_object_signing_alg:
          type: string
          enum:
          - HS256
          - HS384
          - HS512
          - RS256
          - RS384
          - RS512
          - PS256
          - PS384
          - PS512
          - ES256
          - ES384
          - ES512
          - none
          default: none
        request_object_encryption_alg:
          type: string
          enum:
          - RSA1_5
          - RSA-OAEP
          - RSA-OAEP-256
          - ECDH-ES
          - ECDH-ES+A128KW
          - ECDH-ES+A192KW
          - ECDH-ES+A256KW
          - A128KW
          - A192KW
          - A256KW
          - A128GCMKW
          - A192GCMKW
          - A256GCMKW
          - PBES2-HS256+A128KW
          - PBES2-HS384+A192KW
          - PBES2-HS512+A256KW
          - dir
          - none
          default: none
        request_object_encryption_enc:
          type: string
          enum:
          - A128CBC-HS256
          - A192CBC-HS384
          - A192CBC-HS512
          - A128GCM
          - A192GCM
          - A256GCM
          - none
          default: none
        token_endpoint_auth_method:
          type: string
          enum:
          - client_secret_post
          - client_secret_basic
          - client_secret_jwt
          - private_key_jwt
          - none
          default: client_secret_basic
        token_endpoint_auth_signing_alg:
          type: string
          enum:
          - HS256
          - HS384
          - HS512
          - RS256
          - RS384
          - RS512
          - PS256
          - PS384
          - PS512
          - ES256
          - ES384
          - ES512
          - none
          default: none
        default_max_age:
          type: integer
          format: int64
          minimum: 0
          default: 0
        require_auth_time:
          type: boolean
          default: false
        default_acr_values:
          type: array
          uniqueItems: true
          items:
            type: string
        initiate_login_uri:
          type: string
          format: uriHttps
        request_uris:
          type: array
          uniqueItems: true
          items:
            type: string
            format: uri
    NewClientResponse:
      required:
      - client_id
      - client_secret_expires_at
      properties:
        client_id:
          type: string
        client_secret:
          type: string
          format: password
        registration_access_token:
          type: string
          format: password
        registration_client_uri:
          type: string
        client_id_issued_at:
          type: integer
          format: int64
          minimum: 0
        client_secret_expires_at:
          type: integer
          format: int64
          minimum: 0
    ReadClientResponse:
      allOf:
      - $ref: "#/components/schemas/NewClientRequest"
    ErrorResponse:
      required:
      - error
      - error_description
      properties:
        error:
          type: string
        error_description:
          type: string