server:
  port: ${proxy.port:8080}

client:
  host: ${client.service.host:localhost}
  port: ${client.service.port:35027}

discovery:
  host: ${discovery.service.host:localhost}
  port: ${discovery.service.port:35028}

zuul:
  routes:
    authorizeEndpoint:
      path: /
      url: http://${authorize.endpoint.host:localhost}:${authorize.endpoint.port:8080}/oauth/authorize

ribbon:
  okhttp:
    enabled: true