server:
  port: ${service.port:8081}

spring:
  redis:
    database: ${redis.database:0}
    host: ${redis.host:localhost}
    port: ${redis.port:6379}

service:
  name: AuthorizeProxy
  signingKey: ${service.secret:NjhhMjJjMGFkZjhkNDA5MThlYTVkMTMzMmNhZGNiNTY=}

client:
  host: ${client.service.host:localhost}
  port: ${client.service.port:35027}

discovery:
  host: ${discovery.service.host:localhost}
  port: ${discovery.service.port:35028}

login:
  url: ${login.service.url:http://localhost:8888}
  jwks: ${login.service.jwks:}

consent:
  url: ${consent.service.url:http://localhost:9999}
  jwks: ${consent.service.jwks:}

authorize:
  jwks: ${authorize.service.jwks:}

zuul:
  routes:
    authorizeEndpoint:
      path: /
      url: http://${authorize.endpoint.host:localhost}:${authorize.endpoint.port:8080}/oauth/authorize

ribbon:
  okhttp:
    enabled: true