spring.profiles.active: dummy

server:
  port: ${proxy.port:8080}

client:
  host: ${client.service.host:localhost}
  port: ${client.service.port:35027}

discovery:
  host: ${discovery.service.host:localhost}
  port: ${discovery.service.port:35028}

zuul:
  routes:
    tokenEndpoint:
      path: /
      url: http://${token.endpoint.host:localhost}:${token.endpoint.port:8080}/oauth/token

ribbon:
  okhttp:
    enabled: true